kramdown:
  input: GFM
  toc_levels: 2..3

baseurl: "/beanstalk"
layouts_dir: ".shared/layout"
includes_dir: ".shared/includes"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "vendor"]
safe: true

repository: amphp/beanstalk
gems:
 - "jekyll-github-metadata"
 - "jekyll-relative-links"

defaults:
 - scope:
     path: ""
     type: "pages"
   values:
     layout: "docs"
     description: "amphp/beanstalk is an asynchronous Beanstalk client for Amp."
     keywords: ['amphp', 'amp', 'beanstalk', 'beanstalkd', 'client', 'php', 'queue', 'tube', 'jobs', 'async']

shared_asset_path: "/beanstalk/asset"
